apiVersion: apps/v1
kind: Deployment
metadata:
   name: urachatmonitor-deploy
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         ucm: web
   template:
      metadata:
         labels:
            ucm: web
      spec:
         containers:
            - name: urachatmonitor-container
              image: mcjgalvao/urachatmonitor-server:v1.0
              imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
   name: urachatmonitor-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      ucm: web
   ports:
      - port: 8001
        targetPort: 8001
        nodePort: 30001